### ISSUE TITLE
Proof of Concept Plant Monitoring

### ISSUE THREAD

**Issue by Machriam** [Machriam/PlantMonitor#30]
- With the completion of #13 video capturing is now possible
- With #6 we can control the motor with the device
- Next a proof of concept implementation of actually recording the plants is required:
  - [x] Setup of the Gateway Server, see #33
  - [x] The Gateway Server must have a way to configure secrets, which are preserved, see #34
  - [x] The images should be streamed to the browser in the preview. It should not be important, whether the computer is in the same network as the devices. The Gatewayserver should forward the images to the client. See: #37
    - When streaming over WLAN it is preferable, that the Gatewayserver creates its own WLAN and the devices are directly connected to the Gatewayserver without a router
    - Picture transmission performance is roughly doubled, when the picture stream is displayed on the Gatewayserver compared to another device in the WLAN
    - When a device streams to another device, the packets still go through the Gatewayserver, increasing the transmission load of the WLAN by factor 2
  - [x] A replay of the movement should be possible in the browser with simple setting of start step cout, end step count and intermediate step count to briefly pause on
